//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IRLib.wsPhones {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PhoneModelServiceImplServiceSoapBinding", Namespace="http://webservice.ticketsender.edeploy/")]
    public partial class PhoneModelServiceImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getExceptionModelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getModelsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getModelsWithPictureOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVendorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getExceptionModelsWithPictureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PhoneModelServiceImplService() {
            this.Url = global::IRLib.Properties.Settings.Default.IRLib_wsPhones1_PhoneModelServiceImplService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getExceptionModelsCompletedEventHandler getExceptionModelsCompleted;
        
        /// <remarks/>
        public event getModelsCompletedEventHandler getModelsCompleted;
        
        /// <remarks/>
        public event getModelsWithPictureCompletedEventHandler getModelsWithPictureCompleted;
        
        /// <remarks/>
        public event getVendorsCompletedEventHandler getVendorsCompleted;
        
        /// <remarks/>
        public event getExceptionModelsWithPictureCompletedEventHandler getExceptionModelsWithPictureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ticketsender.edeploy/", ResponseNamespace="http://webservice.ticketsender.edeploy/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneModel[] getExceptionModels([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] modelsRequest request) {
            object[] results = this.Invoke("getExceptionModels", new object[] {
                        request});
            return ((phoneModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getExceptionModelsAsync(modelsRequest request) {
            this.getExceptionModelsAsync(request, null);
        }
        
        /// <remarks/>
        public void getExceptionModelsAsync(modelsRequest request, object userState) {
            if ((this.getExceptionModelsOperationCompleted == null)) {
                this.getExceptionModelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExceptionModelsOperationCompleted);
            }
            this.InvokeAsync("getExceptionModels", new object[] {
                        request}, this.getExceptionModelsOperationCompleted, userState);
        }
        
        private void OngetExceptionModelsOperationCompleted(object arg) {
            if ((this.getExceptionModelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExceptionModelsCompleted(this, new getExceptionModelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ticketsender.edeploy/", ResponseNamespace="http://webservice.ticketsender.edeploy/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneModel[] getModels([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] modelsRequest request) {
            object[] results = this.Invoke("getModels", new object[] {
                        request});
            return ((phoneModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getModelsAsync(modelsRequest request) {
            this.getModelsAsync(request, null);
        }
        
        /// <remarks/>
        public void getModelsAsync(modelsRequest request, object userState) {
            if ((this.getModelsOperationCompleted == null)) {
                this.getModelsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetModelsOperationCompleted);
            }
            this.InvokeAsync("getModels", new object[] {
                        request}, this.getModelsOperationCompleted, userState);
        }
        
        private void OngetModelsOperationCompleted(object arg) {
            if ((this.getModelsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getModelsCompleted(this, new getModelsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ticketsender.edeploy/", ResponseNamespace="http://webservice.ticketsender.edeploy/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneModel[] getModelsWithPicture([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] modelsRequest request) {
            object[] results = this.Invoke("getModelsWithPicture", new object[] {
                        request});
            return ((phoneModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getModelsWithPictureAsync(modelsRequest request) {
            this.getModelsWithPictureAsync(request, null);
        }
        
        /// <remarks/>
        public void getModelsWithPictureAsync(modelsRequest request, object userState) {
            if ((this.getModelsWithPictureOperationCompleted == null)) {
                this.getModelsWithPictureOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetModelsWithPictureOperationCompleted);
            }
            this.InvokeAsync("getModelsWithPicture", new object[] {
                        request}, this.getModelsWithPictureOperationCompleted, userState);
        }
        
        private void OngetModelsWithPictureOperationCompleted(object arg) {
            if ((this.getModelsWithPictureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getModelsWithPictureCompleted(this, new getModelsWithPictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ticketsender.edeploy/", ResponseNamespace="http://webservice.ticketsender.edeploy/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getVendors([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] vendorsRequest request) {
            object[] results = this.Invoke("getVendors", new object[] {
                        request});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getVendorsAsync(vendorsRequest request) {
            this.getVendorsAsync(request, null);
        }
        
        /// <remarks/>
        public void getVendorsAsync(vendorsRequest request, object userState) {
            if ((this.getVendorsOperationCompleted == null)) {
                this.getVendorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVendorsOperationCompleted);
            }
            this.InvokeAsync("getVendors", new object[] {
                        request}, this.getVendorsOperationCompleted, userState);
        }
        
        private void OngetVendorsOperationCompleted(object arg) {
            if ((this.getVendorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVendorsCompleted(this, new getVendorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.ticketsender.edeploy/", ResponseNamespace="http://webservice.ticketsender.edeploy/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("response", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public phoneModel[] getExceptionModelsWithPicture([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] modelsRequest request) {
            object[] results = this.Invoke("getExceptionModelsWithPicture", new object[] {
                        request});
            return ((phoneModel[])(results[0]));
        }
        
        /// <remarks/>
        public void getExceptionModelsWithPictureAsync(modelsRequest request) {
            this.getExceptionModelsWithPictureAsync(request, null);
        }
        
        /// <remarks/>
        public void getExceptionModelsWithPictureAsync(modelsRequest request, object userState) {
            if ((this.getExceptionModelsWithPictureOperationCompleted == null)) {
                this.getExceptionModelsWithPictureOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetExceptionModelsWithPictureOperationCompleted);
            }
            this.InvokeAsync("getExceptionModelsWithPicture", new object[] {
                        request}, this.getExceptionModelsWithPictureOperationCompleted, userState);
        }
        
        private void OngetExceptionModelsWithPictureOperationCompleted(object arg) {
            if ((this.getExceptionModelsWithPictureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getExceptionModelsWithPictureCompleted(this, new getExceptionModelsWithPictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ticketsender.edeploy/")]
    public partial class modelsRequest {
        
        private int companyIdField;
        
        private bool companyIdFieldSpecified;
        
        private string usernameField;
        
        private string passwordField;
        
        private string vendorNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companyIdSpecified {
            get {
                return this.companyIdFieldSpecified;
            }
            set {
                this.companyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vendorName {
            get {
                return this.vendorNameField;
            }
            set {
                this.vendorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ticketsender.edeploy/")]
    public partial class vendorsRequest {
        
        private int companyIdField;
        
        private bool companyIdFieldSpecified;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool companyIdSpecified {
            get {
                return this.companyIdFieldSpecified;
            }
            set {
                this.companyIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.ticketsender.edeploy/")]
    public partial class phoneModel {
        
        private int idField;
        
        private string imageURLField;
        
        private string nameField;
        
        private string thumbURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string imageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string thumbURL {
            get {
                return this.thumbURLField;
            }
            set {
                this.thumbURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getExceptionModelsCompletedEventHandler(object sender, getExceptionModelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExceptionModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExceptionModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public phoneModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((phoneModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getModelsCompletedEventHandler(object sender, getModelsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getModelsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getModelsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public phoneModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((phoneModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getModelsWithPictureCompletedEventHandler(object sender, getModelsWithPictureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getModelsWithPictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getModelsWithPictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public phoneModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((phoneModel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getVendorsCompletedEventHandler(object sender, getVendorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVendorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVendorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getExceptionModelsWithPictureCompletedEventHandler(object sender, getExceptionModelsWithPictureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getExceptionModelsWithPictureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getExceptionModelsWithPictureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public phoneModel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((phoneModel[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
