//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mpocket.com.br:8080/TicketSender/Services/PhoneModelService")]
        public string IRLib_wsPhones_PhoneModelServiceImplService {
            get {
                return ((string)(this["IRLib_wsPhones_PhoneModelServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://edeploy.mpocket.com.br:8080/TicketSendSystem/Services/TicketSendSystemServ" +
            "ice")]
        public string IRLib_wsTicket_TicketSendSystemServiceImplService {
            get {
                return ((string)(this["IRLib_wsTicket_TicketSendSystemServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mpocket.com.br:8080/TicketSender/Services/PhoneModelService")]
        public string IRLib_wsPhones1_PhoneModelServiceImplService {
            get {
                return ((string)(this["IRLib_wsPhones1_PhoneModelServiceImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.mondialticket.com.br/ticketprotectorwebservice/TicketProtector.asmx")]
        public string IRLib_Mondial_TicketProtectorWebService {
            get {
                return ((string)(this["IRLib_Mondial_TicketProtectorWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://187.84.229.3:7003/WSCinema.ws")]
        public string IRLib_wsCinema_WSCinema {
            get {
                return ((string)(this["IRLib_wsCinema_WSCinema"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pal-test.adyen.com/pal/servlet/soap/Payment")]
        public string IRLib_wsAdyenSandBox_Payment {
            get {
                return ((string)(this["IRLib_wsAdyenSandBox_Payment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pal-live.adyen.com/pal/servlet/soap/Payment")]
        public string IRLib_wsAdyen_Payment {
            get {
                return ((string)(this["IRLib_wsAdyen_Payment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.72.6.8/Circus/ws.php?class=WSBase")]
        public string IRLib_FonteNovaService_WSBase {
            get {
                return ((string)(this["IRLib_FonteNovaService_WSBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ingressorapido.com.br/services/ServicoDadosHomologacao/ServicoDados.as" +
            "mx")]
        public string IRLib_ServicoDados_ServicoDados {
            get {
                return ((string)(this["IRLib_ServicoDados_ServicoDados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.ingressorapido.com.br/wscep/buscacep.asmx")]
        public string IRLib_wsCEP_BuscaCEP {
            get {
                return ((string)(this["IRLib_wsCEP_BuscaCEP"]));
            }
        }
    }
}
