//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIUsuario
    {
        public APIUsuario()
        {
            this.APIUsuarioToken = new HashSet<APIUsuarioToken>();
        }
    
        public int ID { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public bool Ativo { get; set; }
        public int TipoAcesso { get; set; }
        public string DominiosOrigem { get; set; }
        public string IPOrigem { get; set; }
        public int UsuarioID { get; set; }
        public int LojaID { get; set; }
        public int CanalID { get; set; }
        public int HorasExpiracaoToken { get; set; }
        public int SiteID { get; set; }
        public virtual ICollection<APIUsuarioToken> APIUsuarioToken { get; set; }
    }
}
