//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apresentacao
    {
        public Apresentacao()
        {
            this.Setor = new HashSet<Setor>();
            this.PrecoParceiroMidia = new HashSet<PrecoParceiroMidia>();
            this.Preco = new HashSet<Preco>();
        }
    
        public int ID { get; set; }
        public int IR_ApresentacaoID { get; set; }
        public string Horario { get; set; }
        public int EventoID { get; set; }
        public bool UsarEsquematico { get; set; }
        public string Programacao { get; set; }
        public string CodigoProgramacao { get; set; }
        public Nullable<int> CalcDiaDaSemana { get; set; }
        public Nullable<System.DateTime> CalcHorario { get; set; }

        public virtual Evento Evento { get; set; }
        public virtual ICollection<Setor> Setor { get; set; }
        public virtual ICollection<PrecoParceiroMidia> PrecoParceiroMidia { get; set; }
        public virtual ICollection<Preco> Preco { get; set; }
    }
}
