//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int ID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Codigo { get; set; }
        public Nullable<int> LugarID { get; set; }
        public Nullable<int> EventoID { get; set; }
        public Nullable<int> IngressoID { get; set; }
        public string TipoLugar { get; set; }
        public Nullable<int> ApresentacaoID { get; set; }
        public Nullable<int> SetorID { get; set; }
        public Nullable<int> PrecoID { get; set; }
        public Nullable<int> LocalID { get; set; }
        public string Local { get; set; }
        public string Evento { get; set; }
        public string ApresentacaoDataHora { get; set; }
        public string Setor { get; set; }
        public string PrecoNome { get; set; }
        public string TimeStamp { get; set; }
        public Nullable<decimal> PrecoValor { get; set; }
        public decimal TaxaConveniencia { get; set; }
        public string SessionID { get; set; }
        public string Status { get; set; }
        public string TagOrigem { get; set; }
        public string PacoteGrupo { get; set; }
        public string PacoteNome { get; set; }
        public Nullable<int> Grupo { get; set; }
        public Nullable<int> Classificacao { get; set; }
        public Nullable<int> PrecoExclusivoCodigoID { get; set; }
        public string LocalImagemNome { get; set; }
        public Nullable<int> ValeIngressoTipoID { get; set; }
        public string ValidadeData { get; set; }
        public string ValeIngressoNome { get; set; }
        public Nullable<int> ValidadeDiasImpressao { get; set; }
        public string Acumulativo { get; set; }
        public Nullable<int> ValeIngressoID { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<int> CotaItemID { get; set; }
        public Nullable<int> CotaItemIDAPS { get; set; }
        public Nullable<int> IsSpecial { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public Nullable<int> SerieID { get; set; }
        public Nullable<int> DonoID { get; set; }
        public string DonoCPF { get; set; }
        public string CodigoPromocional { get; set; }
        public Nullable<bool> CotaVerificada { get; set; }
        public Nullable<decimal> ValorTaxaProcessamento { get; set; }
        public Nullable<int> PacoteID { get; set; }
        public Nullable<int> GerenciamentoIngressosID { get; set; }
        public Nullable<int> VoucherID { get; set; }
        public string CodigoBarra { get; set; }
    }
}
