//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestaqueConceitual
    {
        public DestaqueConceitual()
        {
            this.DestaqueConceitualRegiao = new HashSet<DestaqueConceitualRegiao>();
        }
    
        public int ID { get; set; }
        public string Imagem { get; set; }
        public string Fundo { get; set; }
        public string Titulo { get; set; }
        public string Subtitulo { get; set; }
        public string LinkURL { get; set; }
        public string LinkLabel { get; set; }
        public string LinkFundo { get; set; }
        public bool Publicado { get; set; }
    
        public virtual ICollection<DestaqueConceitualRegiao> DestaqueConceitualRegiao { get; set; }
    }
}
