//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Cidade = new HashSet<Cidade>();
        }
    
        public int ID { get; set; }
        public string Sigla { get; set; }
    
        public virtual ICollection<Cidade> Cidade { get; set; }
    }
}
