//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstornoHistoricoPlanilhas
    {
        public int ID { get; set; }
        public string Bandeira { get; set; }
        public string ArquivoEnvio { get; set; }
        public string EmailEnvio { get; set; }
        public System.DateTime DataEnvio { get; set; }
    }
}
