//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using IngressoRapido.Lib;

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Evento
    {
        public Evento()
        {
            this.Apresentacao = new HashSet<Apresentacao>();
            this.NewsAssinante = new HashSet<NewsAssinante>();
            this.DestaqueRegiao = new HashSet<DestaqueRegiao>();
            this.Pacote = new HashSet<PacoteRetorno>();
            this.Serie = new HashSet<Serie>();
        }

        public int ID { get; set; }
        public int IR_EventoID { get; set; }
        public string Nome { get; set; }
        public int LocalID { get; set; }
        public Nullable<int> TipoID { get; set; }
        public string Release { get; set; }
        public string Obs { get; set; }
        public string Imagem { get; set; }
        public Nullable<bool> Destaque { get; set; }
        public Nullable<int> Prioridade { get; set; }
        public Nullable<bool> EntregaGratuita { get; set; }
        public Nullable<bool> RetiradaBilheteria { get; set; }
        public Nullable<bool> DisponivelAvulso { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public Nullable<int> PublicarSemVendaMotivo { get; set; }
        public string Publicar { get; set; }
        public Nullable<int> SubtipoID { get; set; }
        public string DataAberturaVenda { get; set; }
        public Nullable<int> LocalImagemMapaID { get; set; }
        public string LocalImagemNome { get; set; }
        public Nullable<bool> EscolherLugarMarcado { get; set; }
        public string PalavraChave { get; set; }
        public Nullable<bool> ExibeQuantidade { get; set; }
        public Nullable<bool> BannersPadraoSite { get; set; }
        public Nullable<int> MenorPeriodoEntrega { get; set; }
        public Nullable<int> FilmeID { get; set; }
        public Nullable<bool> PermiteVendaPacote { get; set; }
        public bool PossuiTaxaProcessamento { get; set; }
        public int LimiteMaximoIngressosEvento { get; set; }
        public int LimiteMaximoIngressosEstado { get; set; }
        public string ImagemDestaque { get; set; }
        public bool EntradaFranca { get; set; }
        public bool OcultarHoraApresentacao { get; set; }

        public virtual ICollection<PacoteRetorno> Pacote { get; set; }
        public virtual ICollection<Serie> Serie { get; set; }
        public virtual ICollection<Apresentacao> Apresentacao { get; set; }
        public virtual ICollection<NewsAssinante> NewsAssinante { get; set; }
        public virtual ICollection<DestaqueRegiao> DestaqueRegiao { get; set; }
    }
}
