//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaPagamentoSerie
    {
        public int ID { get; set; }
        public int IR_FormaPagamentoSerieID { get; set; }
        public int SerieID { get; set; }
        public int FormaPagamentoID { get; set; }
    }
}
