//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int ID { get; set; }
        public int IR_LocalID { get; set; }
        public string Nome { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string Obs { get; set; }
        public string Endereco { get; set; }
        public string CEP { get; set; }
        public string DDDTelefone { get; set; }
        public string Telefone { get; set; }
        public string ComoChegar { get; set; }
        public decimal TaxaMaximaEmpresa { get; set; }
        public Nullable<bool> BannersPadraoSite { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Pais { get; set; }
        public string Imagem { get; set; }
        public string CodigoPraca { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<decimal> LatitudeAsDecimal { get; set; }
        public Nullable<decimal> LongitudeAsDecimal { get; set; }
    }
}
