//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public string CPF { get; set; }
        public string Senha { get; set; }
        public string Email { get; set; }
        public string DataCadastro { get; set; }
        public string UltimoAcesso { get; set; }
        public string Ativo { get; set; }
        public string StatusAtual { get; set; }
        public string FaceBookUserID { get; set; }
        public string FaceBookUserToken { get; set; }
        public string FaceBookUserInfos { get; set; }
        public string AccountKitId { get; set; }
        public int SiteID { get; set; }
        public Nullable<int> CreatedAPIUsuarioId { get; set; }
        public Nullable<int> LoginAPIUsuarioId { get; set; }
        public string Profissao { get; set; }
        public Nullable<int> SyncStatus { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public string BiletoUuid { get; set; }
        public string respCaptcha { get; set; }
    }
}
