//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRCoreEntitiesSite : DbContext
    {
        public IRCoreEntitiesSite()
            : base("name=IRCoreEntitiesSite")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apresentacao> Apresentacao { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Setor> Setor { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Carrinho> Carrinho { get; set; }
        public virtual DbSet<PontoVenda> PontoVenda { get; set; }
        public virtual DbSet<PontoVendaHorario> PontoVendaHorario { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<DestaqueConceitual> DestaqueConceitual { get; set; }
        public virtual DbSet<DestaqueConceitualRegiao> DestaqueConceitualRegiao { get; set; }
        public virtual DbSet<DestaqueRegiao> DestaqueRegiao { get; set; }
        public virtual DbSet<Regiao> Regiao { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<DuvidasFrequentes> DuvidasFrequentes { get; set; }
        public virtual DbSet<DestaqueLinkRegiao> DestaqueLinkRegiao { get; set; }
        public virtual DbSet<EventoSubtipo> EventoSubtipo { get; set; }
        public virtual DbSet<PontoVendaFormaPgto> PontoVendaFormaPgto { get; set; }
        public virtual DbSet<PontoVendaXFormaPgto> PontoVendaXFormaPgto { get; set; }
        public virtual DbSet<NewsAssinante> NewsAssinante { get; set; }
        public virtual DbSet<PrecoParceiroMidia> PrecoParceiroMidia { get; set; }
        public virtual DbSet<Pacote> Pacote { get; set; }
        public virtual DbSet<PacoteItem> PacoteItem { get; set; }
        public virtual DbSet<Preco> Preco { get; set; }
        public virtual DbSet<NomenclaturaPacote> NomenclaturaPacote { get; set; }
        public virtual DbSet<FormaPagamento> FormaPagamento { get; set; }
        public virtual DbSet<FormaPagamentoCotaItem> FormaPagamentoCotaItem { get; set; }
        public virtual DbSet<FormaPagamentoEvento> FormaPagamentoEvento { get; set; }
        public virtual DbSet<FormaPagamentoSerie> FormaPagamentoSerie { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<BanneriMais> BanneriMais { get; set; }
        public virtual DbSet<APIUsuarioToken> APIUsuarioToken { get; set; }
        public virtual DbSet<APIUsuario> APIUsuario { get; set; }
        public virtual DbSet<vwPrecoCotaControle> vwPrecoCotaControle { get; set; }
    }
}
