//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParceiroMidiaClasse
    {
        public ParceiroMidiaClasse()
        {
            this.ParceiroMidiaClasseSetor = new HashSet<ParceiroMidiaClasseSetor>();
            this.ParceiroMidiaControleIngresso = new HashSet<ParceiroMidiaControleIngresso>();
            this.Voucher = new HashSet<Voucher>();
        }
    
        public int ID { get; set; }
        public int ParceiroMidiaID { get; set; }
        public string Nome { get; set; }
        public int Nivel { get; set; }
    
        public virtual ParceiroMidia ParceiroMidia { get; set; }
        public virtual ICollection<ParceiroMidiaClasseSetor> ParceiroMidiaClasseSetor { get; set; }
        public virtual ICollection<ParceiroMidiaControleIngresso> ParceiroMidiaControleIngresso { get; set; }
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}
