//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontoVendaHorario
    {
        public int ID { get; set; }
        public int IR_PontoVendaHorarioID { get; set; }
        public int PontoVendaID { get; set; }
        public string HorarioInicial { get; set; }
        public string HorarioFinal { get; set; }
        public Nullable<int> DiaSemana { get; set; }
    
        public virtual PontoVenda PontoVenda { get; set; }
    }
}
