//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regiao
    {
        public Regiao()
        {
            this.DestaqueConceitualRegiao = new HashSet<DestaqueConceitualRegiao>();
            this.DestaqueRegiao = new HashSet<DestaqueRegiao>();
            this.DestaqueLinkRegiao = new HashSet<DestaqueLinkRegiao>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<bool> IsGeral { get; set; }
    
        public virtual ICollection<DestaqueConceitualRegiao> DestaqueConceitualRegiao { get; set; }
        public virtual ICollection<DestaqueRegiao> DestaqueRegiao { get; set; }
        public virtual ICollection<DestaqueLinkRegiao> DestaqueLinkRegiao { get; set; }
    }
}
