//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tApresentacao
    {
        public tApresentacao()
        {
            this.tApresentacaoSetor = new HashSet<tApresentacaoSetor>();
            this.tIngresso = new HashSet<tIngresso>();
            this.ParceiroMidiaClasseSetor = new HashSet<ParceiroMidiaClasseSetor>();
            this.tPacoteItem = new HashSet<tPacoteItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EventoID { get; set; }
        public string Horario { get; set; }
        public string DisponivelAjuste { get; set; }
        public string DisponivelRelatorio { get; set; }
        public string Obs { get; set; }
        public string DisponivelVenda { get; set; }
        public Nullable<int> VersaoImagemIngresso { get; set; }
        public Nullable<int> VersaoImagemVale { get; set; }
        public Nullable<int> VersaoImagemVale2 { get; set; }
        public Nullable<int> VersaoImagemVale3 { get; set; }
        public string Impressao { get; set; }
        public Nullable<int> LocalImagemMapaID { get; set; }
        public string DescricaoPadrao { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> UltimoCodigoImpresso { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<int> QuantidadePorCliente { get; set; }
        public Nullable<int> CotaID { get; set; }
        public Nullable<int> MapaEsquematicoID { get; set; }
        public string Programacao { get; set; }
        public string CodigoProgramacao { get; set; }
        public string Sincronizado { get; set; }
        public string Alvara { get; set; }
        public string AVCB { get; set; }
        public Nullable<int> CalcDiaDaSemana { get; set; }
        public Nullable<System.DateTime> CalcHorario { get; set; }
        public string DataEmissaoAlvara { get; set; }
        public string DataValidadeAlvara { get; set; }
        public string DataEmissaoAvcb { get; set; }
        public string DataValidadeAvcb { get; set; }
        public Nullable<int> Lotacao { get; set; }
    
        public virtual ICollection<tApresentacaoSetor> tApresentacaoSetor { get; set; }
        public virtual ICollection<tIngresso> tIngresso { get; set; }
        public virtual ICollection<ParceiroMidiaClasseSetor> ParceiroMidiaClasseSetor { get; set; }
        public virtual tEvento tEvento { get; set; }
        public virtual ICollection<tPacoteItem> tPacoteItem { get; set; }
    }
}
