//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCartao
    {
        public int ID { get; set; }
        public int ClienteID { get; set; }
        public string NroCartao { get; set; }
        public string CheckSumCartao { get; set; }
        public int BandeiraID { get; set; }
        public string Status { get; set; }
        public string Ativo { get; set; }
        public string CartaoCr { get; set; }
        public string CVVCr { get; set; }
        public string DataCr { get; set; }
        public string NomeCartao { get; set; }
    }
}
