//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCompraTemporaria
    {
        public int ID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> FormaPagamentoID { get; set; }
        public Nullable<int> TaxaEntregaID { get; set; }
        public Nullable<int> Parcelas { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string Bandeira { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> BIN { get; set; }
        public string CodigoTrocaFixo { get; set; }
        public Nullable<decimal> TaxaEntregaValor { get; set; }
        public string SomenteVIR { get; set; }
        public string SomenteCortesias { get; set; }
        public Nullable<int> EnderecoID { get; set; }
        public Nullable<int> PDVSelecionado { get; set; }
        public Nullable<int> EntregaControleIDSelecionado { get; set; }
        public string DataSelecionada { get; set; }
        public Nullable<decimal> EntregaValor { get; set; }
        public string CompraGUID { get; set; }
        public Nullable<decimal> DescontoEntrega { get; set; }
    }
}
