//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEntregaControle
    {
        public int ID { get; set; }
        public int EntregaID { get; set; }
        public int EntregaAreaID { get; set; }
        public int PeriodoID { get; set; }
        public int QuantidadeEntregas { get; set; }
        public decimal Valor { get; set; }
        public int DiasTriagem { get; set; }
        public string ProcedimentoEntrega { get; set; }
        public string Ativa { get; set; }
    }
}
