//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEntrega
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> PrazoEntrega { get; set; }
        public string Disponivel { get; set; }
        public string ProcedimentoEntrega { get; set; }
        public string EnviaAlerta { get; set; }
        public string Padrao { get; set; }
        public string PermitirImpressaoInternet { get; set; }
        public string Tipo { get; set; }
        public string Ativo { get; set; }
        public Nullable<int> DiasTriagem { get; set; }
        public Nullable<int> De { get; set; }
        public Nullable<int> Ate { get; set; }
    }
}
