//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEventoEntregaControle
    {
        public int ID { get; set; }
        public int EventoID { get; set; }
        public int EntregaControleID { get; set; }
        public string ProcedimentoEntrega { get; set; }
        public int DiasTriagem { get; set; }
    }
}
