//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEventoTipo
    {
        public tEventoTipo()
        {
            this.tEventoSubtipo = new HashSet<tEventoSubtipo>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Obs { get; set; }
    
        public virtual ICollection<tEventoSubtipo> tEventoSubtipo { get; set; }
    }
}
