//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIngressoCliente
    {
        public int ID { get; set; }
        public Nullable<int> ApresentacaoSetorID { get; set; }
        public Nullable<int> ApresentacaoID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> CotaItemID { get; set; }
        public Nullable<int> IngressoID { get; set; }
        public string CodigoPromocional { get; set; }
        public string CPF { get; set; }
        public Nullable<int> DonoID { get; set; }
    }
}
