//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIngressoLog
    {
        public int ID { get; set; }
        public Nullable<int> IngressoID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string TimeStamp { get; set; }
        public string Acao { get; set; }
        public Nullable<int> PrecoID { get; set; }
        public Nullable<int> CortesiaID { get; set; }
        public Nullable<int> BloqueioID { get; set; }
        public Nullable<int> VendaBilheteriaItemID { get; set; }
        public string Obs { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<int> CaixaID { get; set; }
        public Nullable<int> LojaID { get; set; }
        public Nullable<int> CanalID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string CodigoBarra { get; set; }
        public Nullable<int> CodigoImpressao { get; set; }
        public Nullable<int> MotivoId { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> GerenciamentoIngressosID { get; set; }
        public Nullable<int> AssinaturaClienteID { get; set; }
    }
}
