//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLoja
    {
        public tLoja()
        {
            this.tCaixa = new HashSet<tCaixa>();
        }
    
        public int ID { get; set; }
        public Nullable<int> EstoqueID { get; set; }
        public Nullable<int> CanalID { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CEP { get; set; }
        public string DDDTelefone { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string Obs { get; set; }
        public string TEF { get; set; }
        public string NroEstabelecimento { get; set; }
        public int ComprovanteQuantidade { get; set; }
        public string TEFTipo { get; set; }
        public string numeroPOS { get; set; }
        public Nullable<int> UsuarioPosID { get; set; }
        public string TravaImpressao { get; set; }
    
        public virtual ICollection<tCaixa> tCaixa { get; set; }
        public virtual tCanal tCanal { get; set; }
    }
}
