//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPacoteTemporario
    {
        public string PacoteGrupo { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string SessionID { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<int> QuantidadeP { get; set; }
        public Nullable<int> QuantidadeM { get; set; }
        public Nullable<int> QuantidadeG { get; set; }
        public Nullable<int> QuantidadeGG { get; set; }
        public string TimeStamp { get; set; }
    }
}
