//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSetor
    {
        public tSetor()
        {
            this.tIngresso = new HashSet<tIngresso>();
            this.tMapaEsquematicoSetor = new HashSet<tMapaEsquematicoSetor>();
            this.tApresentacaoSetor = new HashSet<tApresentacaoSetor>();
            this.tLugar = new HashSet<tLugar>();
            this.ParceiroMidiaClasseSetor = new HashSet<ParceiroMidiaClasseSetor>();
            this.tPacoteItem = new HashSet<tPacoteItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LocalID { get; set; }
        public string Nome { get; set; }
        public string NomeInterno { get; set; }
        public string Produto { get; set; }
        public string Descricao { get; set; }
        public string LugarMarcado { get; set; }
        public string ObservacaoImportante { get; set; }
        public Nullable<int> DistanciaPalco { get; set; }
        public string Acesso { get; set; }
        public Nullable<int> VersaoBackground { get; set; }
        public string AprovadoPublicacao { get; set; }
        public string CodigoSala { get; set; }
        public Nullable<int> Capacidade { get; set; }
        public Nullable<int> Linhas { get; set; }
        public Nullable<int> Colunas { get; set; }
    
        public virtual ICollection<tIngresso> tIngresso { get; set; }
        public virtual ICollection<tMapaEsquematicoSetor> tMapaEsquematicoSetor { get; set; }
        public virtual ICollection<tApresentacaoSetor> tApresentacaoSetor { get; set; }
        public virtual ICollection<tLugar> tLugar { get; set; }
        public virtual ICollection<ParceiroMidiaClasseSetor> ParceiroMidiaClasseSetor { get; set; }
        public virtual tLocal tLocal { get; set; }
        public virtual ICollection<tPacoteItem> tPacoteItem { get; set; }
    }
}
