//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tValeIngresso
    {
        public int ID { get; set; }
        public Nullable<int> ValeIngressoTipoID { get; set; }
        public string CodigoTroca { get; set; }
        public string DataCriacao { get; set; }
        public string DataExpiracao { get; set; }
        public string Status { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string SessionID { get; set; }
        public string TimeStampReserva { get; set; }
        public Nullable<int> LojaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> CanalID { get; set; }
        public string ClienteNome { get; set; }
        public string CodigoBarra { get; set; }
    }
}
