//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tValeIngressoTipo
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> ValidadeDiasImpressao { get; set; }
        public string ValidadeData { get; set; }
        public string ClienteTipo { get; set; }
        public string ProcedimentoTroca { get; set; }
        public string SaudacaoPadrao { get; set; }
        public string SaudacaoNominal { get; set; }
        public string QuantidadeLimitada { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string CodigoTrocaFixo { get; set; }
        public string Acumulativo { get; set; }
        public Nullable<int> VersaoImagem { get; set; }
        public Nullable<int> VersaoImagemInternet { get; set; }
        public string ReleaseInternet { get; set; }
        public string PublicarInternet { get; set; }
        public Nullable<int> UltimoCodigoImpresso { get; set; }
        public string TrocaIngresso { get; set; }
        public string TrocaConveniencia { get; set; }
        public string TrocaEntrega { get; set; }
        public string ValorTipo { get; set; }
        public Nullable<decimal> ValorPagamento { get; set; }
    }
}
