//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVendaBilheteriaItem
    {
        public int ID { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<int> PacoteID { get; set; }
        public string Acao { get; set; }
        public Nullable<int> TaxaConveniencia { get; set; }
        public Nullable<decimal> TaxaConvenienciaValor { get; set; }
        public Nullable<int> TaxaComissao { get; set; }
        public Nullable<decimal> ComissaoValor { get; set; }
        public Nullable<int> PacoteGrupo { get; set; }
        public Nullable<int> SerieID { get; set; }
    
        public virtual tVendaBilheteria tVendaBilheteria { get; set; }
        public virtual tPacote tPacote { get; set; }
    }
}
