//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVendaBilheteriaFormaPagamento
    {
        public int ID { get; set; }
        public Nullable<int> FormaPagamentoID { get; set; }
        public Nullable<int> VendaBilheteriaID { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<decimal> Porcentagem { get; set; }
        public Nullable<int> Dias { get; set; }
        public Nullable<decimal> TaxaAdm { get; set; }
        public string IR { get; set; }
        public string DataDeposito { get; set; }
        public Nullable<bool> Atualizado { get; set; }
        public Nullable<int> VIRIngressoID { get; set; }
        public Nullable<int> VendaBilheteriaFormaPagamentoTEFID { get; set; }
        public Nullable<int> ValeIngressoID { get; set; }
        public string MensagemRetorno { get; set; }
        public string HoraTransacao { get; set; }
        public string DataTransacao { get; set; }
        public string CodigoIR { get; set; }
        public string NumeroAutorizacao { get; set; }
        public string NSUHost { get; set; }
        public string NSUSitef { get; set; }
        public string Cupom { get; set; }
        public string DadosConfirmacaoVenda { get; set; }
        public string Rede { get; set; }
        public string CodigoRespostaTransacao { get; set; }
        public Nullable<int> CartaoID { get; set; }
        public string CodigoRespostaVenda { get; set; }
        public string PayerIDPayPal { get; set; }
        public string TokenPayPal { get; set; }
        public string CorrelationID { get; set; }
        public string TransactionID { get; set; }
        public Nullable<decimal> Coeficiente { get; set; }
        public Nullable<decimal> JurosValor { get; set; }
    
        public virtual tVendaBilheteria tVendaBilheteria { get; set; }
        public virtual tFormaPagamento tFormaPagamento { get; set; }
    }
}
