//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVendaBilheteriaEntrega
    {
        public int ID { get; set; }
        public int VendaBilheteriaID { get; set; }
        public string Tipo { get; set; }
        public System.DateTime DataHoraOcorrencia { get; set; }
        public bool EmailEnviado { get; set; }
        public string CodigoRastreamento { get; set; }
        public string StatusTexto { get; set; }
    
        public virtual tVendaBilheteria tVendaBilheteria { get; set; }
    }
}
