//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPrecoCotaControle
    {
        public int EventoID { get; set; }
        public int PrecoID { get; set; }
        public Nullable<bool> TemCota { get; set; }
        public Nullable<bool> CotaLimiteQuantidadeTotal { get; set; }
        public Nullable<bool> CotaLimiteQuantidadeTotalPorCliente { get; set; }
        public Nullable<bool> CotaLimiteQuantidade { get; set; }
        public Nullable<bool> CotaLimiteQuantidadeCliente { get; set; }
        public Nullable<bool> CotaLimiteQuantidadeCodigo { get; set; }
        public Nullable<bool> CotaParceiro { get; set; }
        public Nullable<bool> CotaCartao { get; set; }
        public Nullable<bool> CotaCodigo { get; set; }
        public Nullable<bool> CotaTermo { get; set; }
        public Nullable<bool> CotaNominal { get; set; }
        public Nullable<bool> CotaObrigaNome { get; set; }
        public Nullable<bool> CotaObrigaRG { get; set; }
        public Nullable<bool> CotaObrigaCPF { get; set; }
        public Nullable<bool> CotaObrigaTelefone { get; set; }
        public Nullable<bool> CotaObrigaDataNascimento { get; set; }
        public Nullable<bool> CotaObrigaEmail { get; set; }
    }
}
