//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xEvento
    {
        public int ID { get; set; }
        public int Versao { get; set; }
        public Nullable<int> LocalID { get; set; }
        public Nullable<int> EventoTipoID { get; set; }
        public string Nome { get; set; }
        public string DescricaoResumida { get; set; }
        public string DescricaoDetalhada { get; set; }
        public Nullable<int> VersaoImagemIngresso { get; set; }
        public Nullable<int> VersaoImagemVale { get; set; }
        public string Obs { get; set; }
        public string VendaDistribuida { get; set; }
        public Nullable<int> VersaoImagemVale2 { get; set; }
        public Nullable<int> VersaoImagemVale3 { get; set; }
        public string ImpressaoCodigoBarra { get; set; }
        public string ObrigaCadastroCliente { get; set; }
        public string CodigoBarraEstruturado { get; set; }
        public string DesabilitaAutomatico { get; set; }
        public string Resenha { get; set; }
        public string Publicar { get; set; }
        public string Destaque { get; set; }
        public Nullable<int> PrioridadeDestaque { get; set; }
        public string ImagemInternet { get; set; }
        public string EntregaGratuita { get; set; }
        public string RetiradaBilheteria { get; set; }
        public byte Parcelas { get; set; }
        public string Financeiro { get; set; }
        public string Atencao { get; set; }
        public string PDVSemConveniencia { get; set; }
        public string RetiradaIngresso { get; set; }
        public string MeiaEntrada { get; set; }
        public string Promocoes { get; set; }
        public string AberturaPortoes { get; set; }
        public string DuracaoEvento { get; set; }
        public string Release { get; set; }
        public string DescricaoPadraoApresentacao { get; set; }
        public string Censura { get; set; }
        public string EntradaAcompanhada { get; set; }
        public Nullable<int> PublicarSemVendaMotivo { get; set; }
        public Nullable<int> ContratoID { get; set; }
        public string PermitirVendaSemContrato { get; set; }
        public Nullable<int> EventoSubTipoID { get; set; }
        public Nullable<int> LocalImagemMapaID { get; set; }
        public string DataAberturaVenda { get; set; }
        public Nullable<int> ObrigatoriedadeID { get; set; }
        public string EscolherLugarMarcado { get; set; }
        public Nullable<int> MapaEsquematicoID { get; set; }
        public string PalavraChave { get; set; }
        public string ExibeQuantidade { get; set; }
        public Nullable<int> NivelRisco { get; set; }
        public Nullable<int> MenorPeriodoEntrega { get; set; }
        public string TipoCodigoBarra { get; set; }
        public string HabilitarRetiradaTodosPDV { get; set; }
        public string TipoImpressao { get; set; }
        public string ImagemDestaque { get; set; }
        public Nullable<int> FilmeID { get; set; }
        public string PermiteVendaPacote { get; set; }
        public Nullable<int> LimiteMaximoIngressosEvento { get; set; }
        public Nullable<int> CodigoPos { get; set; }
        public string BaseCalculo { get; set; }
        public string TipoCalculoDesconto { get; set; }
        public string TipoCalculo { get; set; }
        public string Alvara { get; set; }
        public string AVCB { get; set; }
        public string VendaSemAlvara { get; set; }
        public string FonteImposto { get; set; }
        public Nullable<decimal> PorcentagemImposto { get; set; }
        public string DataEmissaoAlvara { get; set; }
        public string DataValidadeAlvara { get; set; }
        public string DataEmissaoAvcb { get; set; }
        public string DataValidadeAvcb { get; set; }
        public Nullable<int> Lotacao { get; set; }
        public Nullable<decimal> PrazoLiberacao { get; set; }
    }
}
