//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRCore.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xUsuario
    {
        public int ID { get; set; }
        public int Versao { get; set; }
        public Nullable<int> EmpresaID { get; set; }
        public string Nome { get; set; }
        public string Sexo { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Status { get; set; }
        public string Validade { get; set; }
        public string ValidoDe { get; set; }
        public string ValidoAte { get; set; }
        public string CodigoTerminal { get; set; }
    }
}
