//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRLib.ServiceNetIntegracao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.net.marketdata.com.br/", ConfigurationName="ServiceNetIntegracao.IngressoRapidoWSEndPoint")]
    public interface IngressoRapidoWSEndPoint {
        
        // CODEGEN: Generating message contract since element name usuario from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidaCPF", ReplyAction="*")]
        IRLib.ServiceNetIntegracao.validaCPFResponse validaCPF(IRLib.ServiceNetIntegracao.validaCPF request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaCPF {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaCPF", Namespace="http://impl.net.marketdata.com.br/", Order=0)]
        public IRLib.ServiceNetIntegracao.validaCPFBody Body;
        
        public validaCPF() {
        }
        
        public validaCPF(IRLib.ServiceNetIntegracao.validaCPFBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaCPFBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cpf;
        
        public validaCPFBody() {
        }
        
        public validaCPFBody(string usuario, string senha, string cpf) {
            this.usuario = usuario;
            this.senha = senha;
            this.cpf = cpf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validaCPFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validaCPFResponse", Namespace="http://impl.net.marketdata.com.br/", Order=0)]
        public IRLib.ServiceNetIntegracao.validaCPFResponseBody Body;
        
        public validaCPFResponse() {
        }
        
        public validaCPFResponse(IRLib.ServiceNetIntegracao.validaCPFResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class validaCPFResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public validaCPFResponseBody() {
        }
        
        public validaCPFResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngressoRapidoWSEndPointChannel : IRLib.ServiceNetIntegracao.IngressoRapidoWSEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngressoRapidoWSEndPointClient : System.ServiceModel.ClientBase<IRLib.ServiceNetIntegracao.IngressoRapidoWSEndPoint>, IRLib.ServiceNetIntegracao.IngressoRapidoWSEndPoint {
        
        public IngressoRapidoWSEndPointClient() {
        }
        
        public IngressoRapidoWSEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngressoRapidoWSEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngressoRapidoWSEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngressoRapidoWSEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IRLib.ServiceNetIntegracao.validaCPFResponse IRLib.ServiceNetIntegracao.IngressoRapidoWSEndPoint.validaCPF(IRLib.ServiceNetIntegracao.validaCPF request) {
            return base.Channel.validaCPF(request);
        }
        
        public int validaCPF(string usuario, string senha, string cpf) {
            IRLib.ServiceNetIntegracao.validaCPF inValue = new IRLib.ServiceNetIntegracao.validaCPF();
            inValue.Body = new IRLib.ServiceNetIntegracao.validaCPFBody();
            inValue.Body.usuario = usuario;
            inValue.Body.senha = senha;
            inValue.Body.cpf = cpf;
            IRLib.ServiceNetIntegracao.validaCPFResponse retVal = ((IRLib.ServiceNetIntegracao.IngressoRapidoWSEndPoint)(this)).validaCPF(inValue);
            return retVal.Body.@return;
        }
    }
}
