//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IRLib.wsCinema {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSCinemaSoap", Namespace="http://tempuri.org/")]
    public partial class WSCinema : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_Cinema_SalasOperationCompleted;
        
        private System.Threading.SendOrPostCallback Set_Cinema_CancelaVendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Cinema_VagasProgOperationCompleted;
        
        private System.Threading.SendOrPostCallback Set_Cinema_RealizaVendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Cinema_FilmesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Set_Cinema_ReservaLugaresOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Cinema_LugarProgOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Cinema_OnLineOperationCompleted;
        
        private System.Threading.SendOrPostCallback Get_Cinema_ProgramacaoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSCinema() {
            this.Url = global::IRLib.Properties.Settings.Default.IRLib_wsCinema_WSCinema;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_Cinema_SalasCompletedEventHandler Get_Cinema_SalasCompleted;
        
        /// <remarks/>
        public event Set_Cinema_CancelaVendaCompletedEventHandler Set_Cinema_CancelaVendaCompleted;
        
        /// <remarks/>
        public event Get_Cinema_VagasProgCompletedEventHandler Get_Cinema_VagasProgCompleted;
        
        /// <remarks/>
        public event Set_Cinema_RealizaVendaCompletedEventHandler Set_Cinema_RealizaVendaCompleted;
        
        /// <remarks/>
        public event Get_Cinema_FilmesCompletedEventHandler Get_Cinema_FilmesCompleted;
        
        /// <remarks/>
        public event Set_Cinema_ReservaLugaresCompletedEventHandler Set_Cinema_ReservaLugaresCompleted;
        
        /// <remarks/>
        public event Get_Cinema_LugarProgCompletedEventHandler Get_Cinema_LugarProgCompleted;
        
        /// <remarks/>
        public event Get_Cinema_OnLineCompletedEventHandler Get_Cinema_OnLineCompleted;
        
        /// <remarks/>
        public event Get_Cinema_ProgramacaoCompletedEventHandler Get_Cinema_ProgramacaoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_Salas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_Salas Get_Cinema_Salas(CINE_AUTENTICA AUTENTICACAO, CINE_GETSALAS GETSALAS) {
            object[] results = this.Invoke("Get_Cinema_Salas", new object[] {
                        AUTENTICACAO,
                        GETSALAS});
            return ((ReturnOfGet_Cinema_Salas)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_SalasAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETSALAS GETSALAS) {
            this.Get_Cinema_SalasAsync(AUTENTICACAO, GETSALAS, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_SalasAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETSALAS GETSALAS, object userState) {
            if ((this.Get_Cinema_SalasOperationCompleted == null)) {
                this.Get_Cinema_SalasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_SalasOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_Salas", new object[] {
                        AUTENTICACAO,
                        GETSALAS}, this.Get_Cinema_SalasOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_SalasOperationCompleted(object arg) {
            if ((this.Get_Cinema_SalasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_SalasCompleted(this, new Get_Cinema_SalasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_Cinema_CancelaVenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfSet_Cinema_CancelaVenda Set_Cinema_CancelaVenda(CINE_AUTENTICA AUTENTICACAO, CINE_CANCVENDA CANCVENDA) {
            object[] results = this.Invoke("Set_Cinema_CancelaVenda", new object[] {
                        AUTENTICACAO,
                        CANCVENDA});
            return ((ReturnOfSet_Cinema_CancelaVenda)(results[0]));
        }
        
        /// <remarks/>
        public void Set_Cinema_CancelaVendaAsync(CINE_AUTENTICA AUTENTICACAO, CINE_CANCVENDA CANCVENDA) {
            this.Set_Cinema_CancelaVendaAsync(AUTENTICACAO, CANCVENDA, null);
        }
        
        /// <remarks/>
        public void Set_Cinema_CancelaVendaAsync(CINE_AUTENTICA AUTENTICACAO, CINE_CANCVENDA CANCVENDA, object userState) {
            if ((this.Set_Cinema_CancelaVendaOperationCompleted == null)) {
                this.Set_Cinema_CancelaVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_Cinema_CancelaVendaOperationCompleted);
            }
            this.InvokeAsync("Set_Cinema_CancelaVenda", new object[] {
                        AUTENTICACAO,
                        CANCVENDA}, this.Set_Cinema_CancelaVendaOperationCompleted, userState);
        }
        
        private void OnSet_Cinema_CancelaVendaOperationCompleted(object arg) {
            if ((this.Set_Cinema_CancelaVendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_Cinema_CancelaVendaCompleted(this, new Set_Cinema_CancelaVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_VagasProg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_VagasProg Get_Cinema_VagasProg(CINE_AUTENTICA AUTENTICACAO, CINE_GETVAGASPROG[] GETVAGASPROG) {
            object[] results = this.Invoke("Get_Cinema_VagasProg", new object[] {
                        AUTENTICACAO,
                        GETVAGASPROG});
            return ((ReturnOfGet_Cinema_VagasProg)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_VagasProgAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETVAGASPROG[] GETVAGASPROG) {
            this.Get_Cinema_VagasProgAsync(AUTENTICACAO, GETVAGASPROG, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_VagasProgAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETVAGASPROG[] GETVAGASPROG, object userState) {
            if ((this.Get_Cinema_VagasProgOperationCompleted == null)) {
                this.Get_Cinema_VagasProgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_VagasProgOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_VagasProg", new object[] {
                        AUTENTICACAO,
                        GETVAGASPROG}, this.Get_Cinema_VagasProgOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_VagasProgOperationCompleted(object arg) {
            if ((this.Get_Cinema_VagasProgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_VagasProgCompleted(this, new Get_Cinema_VagasProgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_Cinema_RealizaVenda", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfSet_Cinema_RealizaVenda Set_Cinema_RealizaVenda(CINE_AUTENTICA AUTENTICACAO, CINE_VENDA VENDA) {
            object[] results = this.Invoke("Set_Cinema_RealizaVenda", new object[] {
                        AUTENTICACAO,
                        VENDA});
            return ((ReturnOfSet_Cinema_RealizaVenda)(results[0]));
        }
        
        /// <remarks/>
        public void Set_Cinema_RealizaVendaAsync(CINE_AUTENTICA AUTENTICACAO, CINE_VENDA VENDA) {
            this.Set_Cinema_RealizaVendaAsync(AUTENTICACAO, VENDA, null);
        }
        
        /// <remarks/>
        public void Set_Cinema_RealizaVendaAsync(CINE_AUTENTICA AUTENTICACAO, CINE_VENDA VENDA, object userState) {
            if ((this.Set_Cinema_RealizaVendaOperationCompleted == null)) {
                this.Set_Cinema_RealizaVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_Cinema_RealizaVendaOperationCompleted);
            }
            this.InvokeAsync("Set_Cinema_RealizaVenda", new object[] {
                        AUTENTICACAO,
                        VENDA}, this.Set_Cinema_RealizaVendaOperationCompleted, userState);
        }
        
        private void OnSet_Cinema_RealizaVendaOperationCompleted(object arg) {
            if ((this.Set_Cinema_RealizaVendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_Cinema_RealizaVendaCompleted(this, new Set_Cinema_RealizaVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_Filmes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_Filmes Get_Cinema_Filmes(CINE_AUTENTICA AUTENTICACAO, CINE_GETFILMES GETFILMES) {
            object[] results = this.Invoke("Get_Cinema_Filmes", new object[] {
                        AUTENTICACAO,
                        GETFILMES});
            return ((ReturnOfGet_Cinema_Filmes)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_FilmesAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETFILMES GETFILMES) {
            this.Get_Cinema_FilmesAsync(AUTENTICACAO, GETFILMES, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_FilmesAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETFILMES GETFILMES, object userState) {
            if ((this.Get_Cinema_FilmesOperationCompleted == null)) {
                this.Get_Cinema_FilmesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_FilmesOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_Filmes", new object[] {
                        AUTENTICACAO,
                        GETFILMES}, this.Get_Cinema_FilmesOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_FilmesOperationCompleted(object arg) {
            if ((this.Get_Cinema_FilmesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_FilmesCompleted(this, new Get_Cinema_FilmesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Set_Cinema_ReservaLugares", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfSet_Cinema_ReservaLugares Set_Cinema_ReservaLugares(CINE_AUTENTICA AUTENTICACAO, CINE_SETRESERVALUGAR[] SETRESERVALUGARES) {
            object[] results = this.Invoke("Set_Cinema_ReservaLugares", new object[] {
                        AUTENTICACAO,
                        SETRESERVALUGARES});
            return ((ReturnOfSet_Cinema_ReservaLugares)(results[0]));
        }
        
        /// <remarks/>
        public void Set_Cinema_ReservaLugaresAsync(CINE_AUTENTICA AUTENTICACAO, CINE_SETRESERVALUGAR[] SETRESERVALUGARES) {
            this.Set_Cinema_ReservaLugaresAsync(AUTENTICACAO, SETRESERVALUGARES, null);
        }
        
        /// <remarks/>
        public void Set_Cinema_ReservaLugaresAsync(CINE_AUTENTICA AUTENTICACAO, CINE_SETRESERVALUGAR[] SETRESERVALUGARES, object userState) {
            if ((this.Set_Cinema_ReservaLugaresOperationCompleted == null)) {
                this.Set_Cinema_ReservaLugaresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSet_Cinema_ReservaLugaresOperationCompleted);
            }
            this.InvokeAsync("Set_Cinema_ReservaLugares", new object[] {
                        AUTENTICACAO,
                        SETRESERVALUGARES}, this.Set_Cinema_ReservaLugaresOperationCompleted, userState);
        }
        
        private void OnSet_Cinema_ReservaLugaresOperationCompleted(object arg) {
            if ((this.Set_Cinema_ReservaLugaresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Set_Cinema_ReservaLugaresCompleted(this, new Set_Cinema_ReservaLugaresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_LugarProg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_LugarProg Get_Cinema_LugarProg(CINE_AUTENTICA AUTENTICACAO, CINE_GETLUGARPROG GETLUGARPROG) {
            object[] results = this.Invoke("Get_Cinema_LugarProg", new object[] {
                        AUTENTICACAO,
                        GETLUGARPROG});
            return ((ReturnOfGet_Cinema_LugarProg)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_LugarProgAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETLUGARPROG GETLUGARPROG) {
            this.Get_Cinema_LugarProgAsync(AUTENTICACAO, GETLUGARPROG, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_LugarProgAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETLUGARPROG GETLUGARPROG, object userState) {
            if ((this.Get_Cinema_LugarProgOperationCompleted == null)) {
                this.Get_Cinema_LugarProgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_LugarProgOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_LugarProg", new object[] {
                        AUTENTICACAO,
                        GETLUGARPROG}, this.Get_Cinema_LugarProgOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_LugarProgOperationCompleted(object arg) {
            if ((this.Get_Cinema_LugarProgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_LugarProgCompleted(this, new Get_Cinema_LugarProgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_OnLine", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_OnLine Get_Cinema_OnLine(CINE_AUTENTICA AUTENTICACAO) {
            object[] results = this.Invoke("Get_Cinema_OnLine", new object[] {
                        AUTENTICACAO});
            return ((ReturnOfGet_Cinema_OnLine)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_OnLineAsync(CINE_AUTENTICA AUTENTICACAO) {
            this.Get_Cinema_OnLineAsync(AUTENTICACAO, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_OnLineAsync(CINE_AUTENTICA AUTENTICACAO, object userState) {
            if ((this.Get_Cinema_OnLineOperationCompleted == null)) {
                this.Get_Cinema_OnLineOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_OnLineOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_OnLine", new object[] {
                        AUTENTICACAO}, this.Get_Cinema_OnLineOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_OnLineOperationCompleted(object arg) {
            if ((this.Get_Cinema_OnLineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_OnLineCompleted(this, new Get_Cinema_OnLineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Cinema_Programacao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReturnOfGet_Cinema_Programacao Get_Cinema_Programacao(CINE_AUTENTICA AUTENTICACAO, CINE_GETPROG GETPROG) {
            object[] results = this.Invoke("Get_Cinema_Programacao", new object[] {
                        AUTENTICACAO,
                        GETPROG});
            return ((ReturnOfGet_Cinema_Programacao)(results[0]));
        }
        
        /// <remarks/>
        public void Get_Cinema_ProgramacaoAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETPROG GETPROG) {
            this.Get_Cinema_ProgramacaoAsync(AUTENTICACAO, GETPROG, null);
        }
        
        /// <remarks/>
        public void Get_Cinema_ProgramacaoAsync(CINE_AUTENTICA AUTENTICACAO, CINE_GETPROG GETPROG, object userState) {
            if ((this.Get_Cinema_ProgramacaoOperationCompleted == null)) {
                this.Get_Cinema_ProgramacaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_Cinema_ProgramacaoOperationCompleted);
            }
            this.InvokeAsync("Get_Cinema_Programacao", new object[] {
                        AUTENTICACAO,
                        GETPROG}, this.Get_Cinema_ProgramacaoOperationCompleted, userState);
        }
        
        private void OnGet_Cinema_ProgramacaoOperationCompleted(object arg) {
            if ((this.Get_Cinema_ProgramacaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_Cinema_ProgramacaoCompleted(this, new Get_Cinema_ProgramacaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_AUTENTICA {
        
        private string uSUARIOField;
        
        private string sENHAField;
        
        /// <remarks/>
        public string USUARIO {
            get {
                return this.uSUARIOField;
            }
            set {
                this.uSUARIOField = value;
            }
        }
        
        /// <remarks/>
        public string SENHA {
            get {
                return this.sENHAField;
            }
            set {
                this.sENHAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_PROG_INGR {
        
        private string cODINGRESSField;
        
        private string vALORField;
        
        private string oRDEMField;
        
        private string eXIBFIDField;
        
        private string nEXIBFIDField;
        
        private string tAXAAUXField;
        
        /// <remarks/>
        public string CODINGRESS {
            get {
                return this.cODINGRESSField;
            }
            set {
                this.cODINGRESSField = value;
            }
        }
        
        /// <remarks/>
        public string VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        public string ORDEM {
            get {
                return this.oRDEMField;
            }
            set {
                this.oRDEMField = value;
            }
        }
        
        /// <remarks/>
        public string EXIBFID {
            get {
                return this.eXIBFIDField;
            }
            set {
                this.eXIBFIDField = value;
            }
        }
        
        /// <remarks/>
        public string NEXIBFID {
            get {
                return this.nEXIBFIDField;
            }
            set {
                this.nEXIBFIDField = value;
            }
        }
        
        /// <remarks/>
        public string TAXAAUX {
            get {
                return this.tAXAAUXField;
            }
            set {
                this.tAXAAUXField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_PROG {
        
        private string iDPROGField;
        
        private string cODSALAField;
        
        private string cODSALA_DESCField;
        
        private string dATASESSAOField;
        
        private string iDFILMEField;
        
        private string iDFILME_DESCField;
        
        private string tEMPOField;
        
        private string cODSISPREField;
        
        private string nVENDLUGAField;
        
        private string nLIBFIDELIDADEField;
        
        private string fERIADOField;
        
        private string cPOCField;
        
        private string vENDE_NUMERADAField;
        
        private CINE_PROG_INGR[] iNGRESSOSField;
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string CODSALA {
            get {
                return this.cODSALAField;
            }
            set {
                this.cODSALAField = value;
            }
        }
        
        /// <remarks/>
        public string CODSALA_DESC {
            get {
                return this.cODSALA_DESCField;
            }
            set {
                this.cODSALA_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string DATASESSAO {
            get {
                return this.dATASESSAOField;
            }
            set {
                this.dATASESSAOField = value;
            }
        }
        
        /// <remarks/>
        public string IDFILME {
            get {
                return this.iDFILMEField;
            }
            set {
                this.iDFILMEField = value;
            }
        }
        
        /// <remarks/>
        public string IDFILME_DESC {
            get {
                return this.iDFILME_DESCField;
            }
            set {
                this.iDFILME_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string TEMPO {
            get {
                return this.tEMPOField;
            }
            set {
                this.tEMPOField = value;
            }
        }
        
        /// <remarks/>
        public string CODSISPRE {
            get {
                return this.cODSISPREField;
            }
            set {
                this.cODSISPREField = value;
            }
        }
        
        /// <remarks/>
        public string NVENDLUGA {
            get {
                return this.nVENDLUGAField;
            }
            set {
                this.nVENDLUGAField = value;
            }
        }
        
        /// <remarks/>
        public string NLIBFIDELIDADE {
            get {
                return this.nLIBFIDELIDADEField;
            }
            set {
                this.nLIBFIDELIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string FERIADO {
            get {
                return this.fERIADOField;
            }
            set {
                this.fERIADOField = value;
            }
        }
        
        /// <remarks/>
        public string CPOC {
            get {
                return this.cPOCField;
            }
            set {
                this.cPOCField = value;
            }
        }
        
        /// <remarks/>
        public string VENDE_NUMERADA {
            get {
                return this.vENDE_NUMERADAField;
            }
            set {
                this.vENDE_NUMERADAField = value;
            }
        }
        
        /// <remarks/>
        public CINE_PROG_INGR[] INGRESSOS {
            get {
                return this.iNGRESSOSField;
            }
            set {
                this.iNGRESSOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_Programacao {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_PROG[] pROGSField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_PROG[] PROGS {
            get {
                return this.pROGSField;
            }
            set {
                this.pROGSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_ERRO {
        
        private string eRRO_CODField;
        
        private string eRRO_DESCField;
        
        /// <remarks/>
        public string ERRO_COD {
            get {
                return this.eRRO_CODField;
            }
            set {
                this.eRRO_CODField = value;
            }
        }
        
        /// <remarks/>
        public string ERRO_DESC {
            get {
                return this.eRRO_DESCField;
            }
            set {
                this.eRRO_DESCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_GETPROG {
        
        private string iDPROGField;
        
        private string dATAINIField;
        
        private string dATAFINField;
        
        private string cODSALAField;
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string DATAINI {
            get {
                return this.dATAINIField;
            }
            set {
                this.dATAINIField = value;
            }
        }
        
        /// <remarks/>
        public string DATAFIN {
            get {
                return this.dATAFINField;
            }
            set {
                this.dATAFINField = value;
            }
        }
        
        /// <remarks/>
        public string CODSALA {
            get {
                return this.cODSALAField;
            }
            set {
                this.cODSALAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_ONLINE {
        
        private string pRACA_CODField;
        
        private string dATA_HORAField;
        
        /// <remarks/>
        public string PRACA_COD {
            get {
                return this.pRACA_CODField;
            }
            set {
                this.pRACA_CODField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_HORA {
            get {
                return this.dATA_HORAField;
            }
            set {
                this.dATA_HORAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_OnLine {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_ONLINE oNLINEField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_ONLINE ONLINE {
            get {
                return this.oNLINEField;
            }
            set {
                this.oNLINEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_LUGARPROG {
        
        private string cODLUGARField;
        
        private string sTATUSField;
        
        /// <remarks/>
        public string CODLUGAR {
            get {
                return this.cODLUGARField;
            }
            set {
                this.cODLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_LugarProg {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_LUGARPROG[] lUGARPROGSField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_LUGARPROG[] LUGARPROGS {
            get {
                return this.lUGARPROGSField;
            }
            set {
                this.lUGARPROGSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_GETLUGARPROG {
        
        private string iDPROGField;
        
        private string sTATUSField;
        
        private string cODLUGARField;
        
        private string iDCOMPRAField;
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string CODLUGAR {
            get {
                return this.cODLUGARField;
            }
            set {
                this.cODLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string IDCOMPRA {
            get {
                return this.iDCOMPRAField;
            }
            set {
                this.iDCOMPRAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfSet_Cinema_ReservaLugares {
        
        private CINE_ERRO[] eRROSField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_SETRESERVALUGAR {
        
        private string iDCOMPRAField;
        
        private string iDPROGField;
        
        private string cODLUGARField;
        
        private string aCAOField;
        
        /// <remarks/>
        public string IDCOMPRA {
            get {
                return this.iDCOMPRAField;
            }
            set {
                this.iDCOMPRAField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string CODLUGAR {
            get {
                return this.cODLUGARField;
            }
            set {
                this.cODLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string ACAO {
            get {
                return this.aCAOField;
            }
            set {
                this.aCAOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_FILME {
        
        private string iDFILMEField;
        
        private string tITULOField;
        
        private string tITULORESUField;
        
        private string dATACADField;
        
        private string dURACAOField;
        
        private string eSTILOField;
        
        private string eSTILO_DESCField;
        
        private string iDADEField;
        
        private string iDADEJUSTIField;
        
        private string sINOPSEField;
        
        private string dUBLADOField;
        
        private string nIERELCODEField;
        
        private string iMDBField;
        
        /// <remarks/>
        public string IDFILME {
            get {
                return this.iDFILMEField;
            }
            set {
                this.iDFILMEField = value;
            }
        }
        
        /// <remarks/>
        public string TITULO {
            get {
                return this.tITULOField;
            }
            set {
                this.tITULOField = value;
            }
        }
        
        /// <remarks/>
        public string TITULORESU {
            get {
                return this.tITULORESUField;
            }
            set {
                this.tITULORESUField = value;
            }
        }
        
        /// <remarks/>
        public string DATACAD {
            get {
                return this.dATACADField;
            }
            set {
                this.dATACADField = value;
            }
        }
        
        /// <remarks/>
        public string DURACAO {
            get {
                return this.dURACAOField;
            }
            set {
                this.dURACAOField = value;
            }
        }
        
        /// <remarks/>
        public string ESTILO {
            get {
                return this.eSTILOField;
            }
            set {
                this.eSTILOField = value;
            }
        }
        
        /// <remarks/>
        public string ESTILO_DESC {
            get {
                return this.eSTILO_DESCField;
            }
            set {
                this.eSTILO_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string IDADE {
            get {
                return this.iDADEField;
            }
            set {
                this.iDADEField = value;
            }
        }
        
        /// <remarks/>
        public string IDADEJUSTI {
            get {
                return this.iDADEJUSTIField;
            }
            set {
                this.iDADEJUSTIField = value;
            }
        }
        
        /// <remarks/>
        public string SINOPSE {
            get {
                return this.sINOPSEField;
            }
            set {
                this.sINOPSEField = value;
            }
        }
        
        /// <remarks/>
        public string DUBLADO {
            get {
                return this.dUBLADOField;
            }
            set {
                this.dUBLADOField = value;
            }
        }
        
        /// <remarks/>
        public string NIERELCODE {
            get {
                return this.nIERELCODEField;
            }
            set {
                this.nIERELCODEField = value;
            }
        }
        
        /// <remarks/>
        public string IMDB {
            get {
                return this.iMDBField;
            }
            set {
                this.iMDBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_Filmes {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_FILME[] fILMESField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_FILME[] FILMES {
            get {
                return this.fILMESField;
            }
            set {
                this.fILMESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_GETFILMES {
        
        private string dATAINIField;
        
        private string dATAFINField;
        
        private string iDFILMEField;
        
        /// <remarks/>
        public string DATAINI {
            get {
                return this.dATAINIField;
            }
            set {
                this.dATAINIField = value;
            }
        }
        
        /// <remarks/>
        public string DATAFIN {
            get {
                return this.dATAFINField;
            }
            set {
                this.dATAFINField = value;
            }
        }
        
        /// <remarks/>
        public string IDFILME {
            get {
                return this.iDFILMEField;
            }
            set {
                this.iDFILMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfSet_Cinema_RealizaVenda {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_VENDA rETVENDAField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_VENDA RETVENDA {
            get {
                return this.rETVENDAField;
            }
            set {
                this.rETVENDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_VENDA {
        
        private string iDMOVIMEField;
        
        private string mOMENTOField;
        
        private string dESCRICAOField;
        
        private string tIPOMOVIMField;
        
        private string iNFOSField;
        
        private string cODFORMAField;
        
        private string mOV_VALORField;
        
        private string mOV_DESCONTOField;
        
        private string mOV_ACRESCIMOField;
        
        private string nT_ASSIDField;
        
        private string nT_ASSNOMEField;
        
        private string nT_ASSCPFField;
        
        private string nT_ASSDOC2Field;
        
        private string nT_CODBARField;
        
        private string nT_TRANSACField;
        
        private string nT_AUTORIZField;
        
        private string nT_IDField;
        
        private string nT_STATUSField;
        
        private string nT_STNOMEField;
        
        private string sIMULARField;
        
        private CINE_VENDAITEM[] iTENSField;
        
        private CINE_VENDAPAGA[] pAGAMENTOSField;
        
        /// <remarks/>
        public string IDMOVIME {
            get {
                return this.iDMOVIMEField;
            }
            set {
                this.iDMOVIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MOMENTO {
            get {
                return this.mOMENTOField;
            }
            set {
                this.mOMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
            }
        }
        
        /// <remarks/>
        public string TIPOMOVIM {
            get {
                return this.tIPOMOVIMField;
            }
            set {
                this.tIPOMOVIMField = value;
            }
        }
        
        /// <remarks/>
        public string INFOS {
            get {
                return this.iNFOSField;
            }
            set {
                this.iNFOSField = value;
            }
        }
        
        /// <remarks/>
        public string CODFORMA {
            get {
                return this.cODFORMAField;
            }
            set {
                this.cODFORMAField = value;
            }
        }
        
        /// <remarks/>
        public string MOV_VALOR {
            get {
                return this.mOV_VALORField;
            }
            set {
                this.mOV_VALORField = value;
            }
        }
        
        /// <remarks/>
        public string MOV_DESCONTO {
            get {
                return this.mOV_DESCONTOField;
            }
            set {
                this.mOV_DESCONTOField = value;
            }
        }
        
        /// <remarks/>
        public string MOV_ACRESCIMO {
            get {
                return this.mOV_ACRESCIMOField;
            }
            set {
                this.mOV_ACRESCIMOField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ASSID {
            get {
                return this.nT_ASSIDField;
            }
            set {
                this.nT_ASSIDField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ASSNOME {
            get {
                return this.nT_ASSNOMEField;
            }
            set {
                this.nT_ASSNOMEField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ASSCPF {
            get {
                return this.nT_ASSCPFField;
            }
            set {
                this.nT_ASSCPFField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ASSDOC2 {
            get {
                return this.nT_ASSDOC2Field;
            }
            set {
                this.nT_ASSDOC2Field = value;
            }
        }
        
        /// <remarks/>
        public string NT_CODBAR {
            get {
                return this.nT_CODBARField;
            }
            set {
                this.nT_CODBARField = value;
            }
        }
        
        /// <remarks/>
        public string NT_TRANSAC {
            get {
                return this.nT_TRANSACField;
            }
            set {
                this.nT_TRANSACField = value;
            }
        }
        
        /// <remarks/>
        public string NT_AUTORIZ {
            get {
                return this.nT_AUTORIZField;
            }
            set {
                this.nT_AUTORIZField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ID {
            get {
                return this.nT_IDField;
            }
            set {
                this.nT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string NT_STATUS {
            get {
                return this.nT_STATUSField;
            }
            set {
                this.nT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public string NT_STNOME {
            get {
                return this.nT_STNOMEField;
            }
            set {
                this.nT_STNOMEField = value;
            }
        }
        
        /// <remarks/>
        public string SIMULAR {
            get {
                return this.sIMULARField;
            }
            set {
                this.sIMULARField = value;
            }
        }
        
        /// <remarks/>
        public CINE_VENDAITEM[] ITENS {
            get {
                return this.iTENSField;
            }
            set {
                this.iTENSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_VENDAPAGA[] PAGAMENTOS {
            get {
                return this.pAGAMENTOSField;
            }
            set {
                this.pAGAMENTOSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_VENDAITEM {
        
        private string dESCRICAOField;
        
        private string iTEMField;
        
        private string tIPOITEMField;
        
        private string pRODUTOField;
        
        private string cODBARRAField;
        
        private string qTDField;
        
        private string vALORUNField;
        
        private string dESCONTOField;
        
        private string aCRESCIMOField;
        
        private string iNFOSField;
        
        private string iDPROGField;
        
        private string iDPROG_DATASESSAOField;
        
        private string iDPROG_CODSALAField;
        
        private string iDPROG_IDFILMEField;
        
        private string cODINGRESSField;
        
        private string cODLUGARField;
        
        private string iDPROMOCAOField;
        
        private string pROMO_CODField;
        
        private string nT_CODBARField;
        
        private string nT_STATUSField;
        
        private string nT_DESCRField;
        
        private string nT_STNOMEField;
        
        /// <remarks/>
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
            }
        }
        
        /// <remarks/>
        public string ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
        
        /// <remarks/>
        public string TIPOITEM {
            get {
                return this.tIPOITEMField;
            }
            set {
                this.tIPOITEMField = value;
            }
        }
        
        /// <remarks/>
        public string PRODUTO {
            get {
                return this.pRODUTOField;
            }
            set {
                this.pRODUTOField = value;
            }
        }
        
        /// <remarks/>
        public string CODBARRA {
            get {
                return this.cODBARRAField;
            }
            set {
                this.cODBARRAField = value;
            }
        }
        
        /// <remarks/>
        public string QTD {
            get {
                return this.qTDField;
            }
            set {
                this.qTDField = value;
            }
        }
        
        /// <remarks/>
        public string VALORUN {
            get {
                return this.vALORUNField;
            }
            set {
                this.vALORUNField = value;
            }
        }
        
        /// <remarks/>
        public string DESCONTO {
            get {
                return this.dESCONTOField;
            }
            set {
                this.dESCONTOField = value;
            }
        }
        
        /// <remarks/>
        public string ACRESCIMO {
            get {
                return this.aCRESCIMOField;
            }
            set {
                this.aCRESCIMOField = value;
            }
        }
        
        /// <remarks/>
        public string INFOS {
            get {
                return this.iNFOSField;
            }
            set {
                this.iNFOSField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROG_DATASESSAO {
            get {
                return this.iDPROG_DATASESSAOField;
            }
            set {
                this.iDPROG_DATASESSAOField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROG_CODSALA {
            get {
                return this.iDPROG_CODSALAField;
            }
            set {
                this.iDPROG_CODSALAField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROG_IDFILME {
            get {
                return this.iDPROG_IDFILMEField;
            }
            set {
                this.iDPROG_IDFILMEField = value;
            }
        }
        
        /// <remarks/>
        public string CODINGRESS {
            get {
                return this.cODINGRESSField;
            }
            set {
                this.cODINGRESSField = value;
            }
        }
        
        /// <remarks/>
        public string CODLUGAR {
            get {
                return this.cODLUGARField;
            }
            set {
                this.cODLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string IDPROMOCAO {
            get {
                return this.iDPROMOCAOField;
            }
            set {
                this.iDPROMOCAOField = value;
            }
        }
        
        /// <remarks/>
        public string PROMO_COD {
            get {
                return this.pROMO_CODField;
            }
            set {
                this.pROMO_CODField = value;
            }
        }
        
        /// <remarks/>
        public string NT_CODBAR {
            get {
                return this.nT_CODBARField;
            }
            set {
                this.nT_CODBARField = value;
            }
        }
        
        /// <remarks/>
        public string NT_STATUS {
            get {
                return this.nT_STATUSField;
            }
            set {
                this.nT_STATUSField = value;
            }
        }
        
        /// <remarks/>
        public string NT_DESCR {
            get {
                return this.nT_DESCRField;
            }
            set {
                this.nT_DESCRField = value;
            }
        }
        
        /// <remarks/>
        public string NT_STNOME {
            get {
                return this.nT_STNOMEField;
            }
            set {
                this.nT_STNOMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_VENDAPAGA {
        
        private string tIPODOCField;
        
        private string dOCUMENTOField;
        
        private string vALORField;
        
        private string vENCIMENTOField;
        
        private string pARCELAField;
        
        private string pARCTOTField;
        
        private string iNFOSField;
        
        private string nET_VALIDADEField;
        
        /// <remarks/>
        public string TIPODOC {
            get {
                return this.tIPODOCField;
            }
            set {
                this.tIPODOCField = value;
            }
        }
        
        /// <remarks/>
        public string DOCUMENTO {
            get {
                return this.dOCUMENTOField;
            }
            set {
                this.dOCUMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string VALOR {
            get {
                return this.vALORField;
            }
            set {
                this.vALORField = value;
            }
        }
        
        /// <remarks/>
        public string VENCIMENTO {
            get {
                return this.vENCIMENTOField;
            }
            set {
                this.vENCIMENTOField = value;
            }
        }
        
        /// <remarks/>
        public string PARCELA {
            get {
                return this.pARCELAField;
            }
            set {
                this.pARCELAField = value;
            }
        }
        
        /// <remarks/>
        public string PARCTOT {
            get {
                return this.pARCTOTField;
            }
            set {
                this.pARCTOTField = value;
            }
        }
        
        /// <remarks/>
        public string INFOS {
            get {
                return this.iNFOSField;
            }
            set {
                this.iNFOSField = value;
            }
        }
        
        /// <remarks/>
        public string NET_VALIDADE {
            get {
                return this.nET_VALIDADEField;
            }
            set {
                this.nET_VALIDADEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_VAGASPROG {
        
        private string iDPROGField;
        
        private string cAPACIDADEField;
        
        private string dISPONIVELField;
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
        
        /// <remarks/>
        public string CAPACIDADE {
            get {
                return this.cAPACIDADEField;
            }
            set {
                this.cAPACIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string DISPONIVEL {
            get {
                return this.dISPONIVELField;
            }
            set {
                this.dISPONIVELField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_VagasProg {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_VAGASPROG[] vAGASPROGSField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_VAGASPROG[] VAGASPROGS {
            get {
                return this.vAGASPROGSField;
            }
            set {
                this.vAGASPROGSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_GETVAGASPROG {
        
        private string iDPROGField;
        
        /// <remarks/>
        public string IDPROG {
            get {
                return this.iDPROGField;
            }
            set {
                this.iDPROGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_RETCANCVENDA {
        
        private string iDMOVIMEField;
        
        /// <remarks/>
        public string IDMOVIME {
            get {
                return this.iDMOVIMEField;
            }
            set {
                this.iDMOVIMEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfSet_Cinema_CancelaVenda {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_RETCANCVENDA rETCANCVENDAField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_RETCANCVENDA RETCANCVENDA {
            get {
                return this.rETCANCVENDAField;
            }
            set {
                this.rETCANCVENDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_CANCVENDA {
        
        private string iDMOVIMEField;
        
        private string mOV_VALORField;
        
        private string nT_CODBARField;
        
        private string nT_IDField;
        
        private string mOTIVOField;
        
        /// <remarks/>
        public string IDMOVIME {
            get {
                return this.iDMOVIMEField;
            }
            set {
                this.iDMOVIMEField = value;
            }
        }
        
        /// <remarks/>
        public string MOV_VALOR {
            get {
                return this.mOV_VALORField;
            }
            set {
                this.mOV_VALORField = value;
            }
        }
        
        /// <remarks/>
        public string NT_CODBAR {
            get {
                return this.nT_CODBARField;
            }
            set {
                this.nT_CODBARField = value;
            }
        }
        
        /// <remarks/>
        public string NT_ID {
            get {
                return this.nT_IDField;
            }
            set {
                this.nT_IDField = value;
            }
        }
        
        /// <remarks/>
        public string MOTIVO {
            get {
                return this.mOTIVOField;
            }
            set {
                this.mOTIVOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_LUGAR {
        
        private string iDLUGARField;
        
        private string cODLUGARField;
        
        private string cODSALAField;
        
        private string cOLUNAField;
        
        private string lINHAField;
        
        private string tIPOField;
        
        /// <remarks/>
        public string IDLUGAR {
            get {
                return this.iDLUGARField;
            }
            set {
                this.iDLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string CODLUGAR {
            get {
                return this.cODLUGARField;
            }
            set {
                this.cODLUGARField = value;
            }
        }
        
        /// <remarks/>
        public string CODSALA {
            get {
                return this.cODSALAField;
            }
            set {
                this.cODSALAField = value;
            }
        }
        
        /// <remarks/>
        public string COLUNA {
            get {
                return this.cOLUNAField;
            }
            set {
                this.cOLUNAField = value;
            }
        }
        
        /// <remarks/>
        public string LINHA {
            get {
                return this.lINHAField;
            }
            set {
                this.lINHAField = value;
            }
        }
        
        /// <remarks/>
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_SALA {
        
        private string cODSALAField;
        
        private string dESCRICAOField;
        
        private string dESCRRESUField;
        
        private string cODPRACAField;
        
        private string cODPRACA_DESCField;
        
        private string cAPACIDADEField;
        
        private string nIECODEField;
        
        private string cODIGOINTField;
        
        private string nVENDLUGAField;
        
        private string cORField;
        
        private string lINHAField;
        
        private string cOLUNAField;
        
        private string dIGITALField;
        
        private CINE_LUGAR[] lUGARESField;
        
        /// <remarks/>
        public string CODSALA {
            get {
                return this.cODSALAField;
            }
            set {
                this.cODSALAField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
            }
        }
        
        /// <remarks/>
        public string DESCRRESU {
            get {
                return this.dESCRRESUField;
            }
            set {
                this.dESCRRESUField = value;
            }
        }
        
        /// <remarks/>
        public string CODPRACA {
            get {
                return this.cODPRACAField;
            }
            set {
                this.cODPRACAField = value;
            }
        }
        
        /// <remarks/>
        public string CODPRACA_DESC {
            get {
                return this.cODPRACA_DESCField;
            }
            set {
                this.cODPRACA_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string CAPACIDADE {
            get {
                return this.cAPACIDADEField;
            }
            set {
                this.cAPACIDADEField = value;
            }
        }
        
        /// <remarks/>
        public string NIECODE {
            get {
                return this.nIECODEField;
            }
            set {
                this.nIECODEField = value;
            }
        }
        
        /// <remarks/>
        public string CODIGOINT {
            get {
                return this.cODIGOINTField;
            }
            set {
                this.cODIGOINTField = value;
            }
        }
        
        /// <remarks/>
        public string NVENDLUGA {
            get {
                return this.nVENDLUGAField;
            }
            set {
                this.nVENDLUGAField = value;
            }
        }
        
        /// <remarks/>
        public string COR {
            get {
                return this.cORField;
            }
            set {
                this.cORField = value;
            }
        }
        
        /// <remarks/>
        public string LINHA {
            get {
                return this.lINHAField;
            }
            set {
                this.lINHAField = value;
            }
        }
        
        /// <remarks/>
        public string COLUNA {
            get {
                return this.cOLUNAField;
            }
            set {
                this.cOLUNAField = value;
            }
        }
        
        /// <remarks/>
        public string DIGITAL {
            get {
                return this.dIGITALField;
            }
            set {
                this.dIGITALField = value;
            }
        }
        
        /// <remarks/>
        public CINE_LUGAR[] LUGARES {
            get {
                return this.lUGARESField;
            }
            set {
                this.lUGARESField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnOfGet_Cinema_Salas {
        
        private CINE_ERRO[] eRROSField;
        
        private CINE_SALA[] sALASField;
        
        /// <remarks/>
        public CINE_ERRO[] ERROS {
            get {
                return this.eRROSField;
            }
            set {
                this.eRROSField = value;
            }
        }
        
        /// <remarks/>
        public CINE_SALA[] SALAS {
            get {
                return this.sALASField;
            }
            set {
                this.sALASField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CINE_GETSALAS {
        
        private string cODPRACAField;
        
        private string cODSALAField;
        
        /// <remarks/>
        public string CODPRACA {
            get {
                return this.cODPRACAField;
            }
            set {
                this.cODPRACAField = value;
            }
        }
        
        /// <remarks/>
        public string CODSALA {
            get {
                return this.cODSALAField;
            }
            set {
                this.cODSALAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_SalasCompletedEventHandler(object sender, Get_Cinema_SalasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_SalasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_SalasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_Salas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_Salas)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Set_Cinema_CancelaVendaCompletedEventHandler(object sender, Set_Cinema_CancelaVendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_Cinema_CancelaVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_Cinema_CancelaVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfSet_Cinema_CancelaVenda Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfSet_Cinema_CancelaVenda)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_VagasProgCompletedEventHandler(object sender, Get_Cinema_VagasProgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_VagasProgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_VagasProgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_VagasProg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_VagasProg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Set_Cinema_RealizaVendaCompletedEventHandler(object sender, Set_Cinema_RealizaVendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_Cinema_RealizaVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_Cinema_RealizaVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfSet_Cinema_RealizaVenda Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfSet_Cinema_RealizaVenda)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_FilmesCompletedEventHandler(object sender, Get_Cinema_FilmesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_FilmesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_FilmesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_Filmes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_Filmes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Set_Cinema_ReservaLugaresCompletedEventHandler(object sender, Set_Cinema_ReservaLugaresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Set_Cinema_ReservaLugaresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Set_Cinema_ReservaLugaresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfSet_Cinema_ReservaLugares Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfSet_Cinema_ReservaLugares)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_LugarProgCompletedEventHandler(object sender, Get_Cinema_LugarProgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_LugarProgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_LugarProgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_LugarProg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_LugarProg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_OnLineCompletedEventHandler(object sender, Get_Cinema_OnLineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_OnLineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_OnLineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_OnLine Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_OnLine)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Get_Cinema_ProgramacaoCompletedEventHandler(object sender, Get_Cinema_ProgramacaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_Cinema_ProgramacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_Cinema_ProgramacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReturnOfGet_Cinema_Programacao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReturnOfGet_Cinema_Programacao)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591
