//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRLib.Paralela
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRLib.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libseppemv.dll,
        ///CliSiTef.ini,
        ///CliSiTef32.dll,
        ///CliSiTef32I.dll,
        ///Daruma32.dll.
        /// </summary>
        internal static string ArquivosBaixarTEF {
            get {
                return ResourceManager.GetString("ArquivosBaixarTEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot;
        ///xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;meta name=ProgId content=Excel.Sheet&gt;
        ///&lt;meta name=Generator content=&quot;Ingresso Rápido&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///&lt;div align=center&gt;
        ///
        ///&lt;table border=1&gt;
        ///
        ///&lt;TABLE border=&quot;1&quot;&gt;
        ///
        ///
        ///&lt;TR&gt;
        ///($titulo$)
        ///($dados$)
        ///&lt;/TABLE&gt;
        ///
        ///&lt;/table&gt;
        ///
        ///&lt;/div&gt;
        ///
        ///&lt;/body&gt;
        ///.
        /// </summary>
        internal static string ExcelExportFile {
            get {
                return ResourceManager.GetString("ExcelExportFile", resourceCulture);
            }
        }
    }
}
